name: Teste SAST HTML e Docker Build/Push

on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip install Flask
        npm install htmlhint --global

    - name: Build Docker image
      run: |
        docker build -t USUARIO/PROJETO:latest .
        docker push USUARIO/PROJETO:latest

  test-job:
    runs-on: ubuntu-latest

    needs: build-job

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip install Flask
        npm install htmlhint --global

    - name: Run SAST test
      run: htmlhint https://example.com/index.html

  deploy-job:
    runs-on: ubuntu-latest

    needs: test-job

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log In to Docker Hub
      uses: docker/login-action@v1
      with:
        username: educordovasilva@hotmail.com
        password: senha-docker-puc

    - name: Build Docker image
      run: |
        docker build -t educordovasilva/somativa02:latest .
        docker run -d -p 8080:80 educordovasilva/somativa02

